# Generated by Django 3.0.6 on 2020-05-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewerage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='controller_x',
            field=models.FloatField(default=31.7760081),
        ),
        migrations.AddField(
            model_name='controller',
            name='controller_y',
            field=models.FloatField(default=35.2353219),
        ),
    ]
