# Generated by Django 3.0.6 on 2020-05-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewerage', '0002_auto_20200517_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='controller_id',
        ),
    ]
