# Generated by Django 3.0.6 on 2020-05-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewerage', '0003_remove_controller_controller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='status',
            field=models.IntegerField(choices=[(1, '1 - GREEN'), (2, '2 - YELLOW'), (3, '3 - ORANGE'), (4, '4 - RED')]),
        ),
    ]
