# Generated by Django 3.0.6 on 2020-05-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imege',
            new_name='image',
        ),
    ]
